name: Sciencecraft
main: de.stonie1901.serverplugin.Main
version: 0.1-Alpha
description: Test
author: stonie1901
categories: [INFO]

commands:
    teamspeak:
        description: Teamspeak Command
        usage: /<command>
        aliases: [ts]
    bukkitserver:
        description: Info Command
        usage: /<command>
        aliases: [bs]
    hilfe:
        description: Hilfe Command
        usage: /<command>
        
permissions:
    sciencecraft.*:
        description: Gives full access
        children:
            sciencecraft.hilfe: true
            sciencecraft.ts: true
            lagmeter.command.lagmem: true
            lagmeter.command.lm: true
            lagmeter.command.ping: true
            lagmeter.command.lping: true
    sciencecraft.help:
        description: Gives access to the /hilfe command
        default: true
    sciencecraft.ts:
        description: Gives access to the /teamspeak command
        default: true
    sciencecraft.premium:
        description: Gives access to the premium command
        default: true
    sciencecraft.user:
        description: Gives access to user commands     
        children:
            sciencecraft.hilfe: true
            sciencecraft.ts: true 